---

jobs:
  include:
    - language: node_js
      node_js:
        - 12
      cache:
        directories:
          - node_modules
      before_script:
        - cd frontend
      script:
        - npm install
        - npm run build
        - npm test

    - language: python
      python:
        - "3.8"
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pytest
