---
jobs:
   include:
    - language: node_js
    node_js:
      - 8
    cache:
    directories:
    - node_modules
    before_script:
      -cd behaviour_mapper/
    script:
      - npm run build
      - npm test
      

    - language: python
      python:
        - "2.7"
        - "3.8"
       before_install:
         - cd backend/
       install: 
         -pip install -r requirements.txt
       script:
         - pytest
